export const TOOL_CATEGORIES = [
  { id: "core", label: "Core Analysis" },
  { id: "strategy", label: "Market & Strategy" },
  { id: "execution", label: "Interview & Execution" },
];

const has = (value) => String(value || "").trim().length > 0;

export const CAREER_LAB_TOOLS = [
  {
    id: "job-parser",
    category: "core",
    title: "Job Parser",
    description:
      "Extract required and preferred skills, responsibilities, and seniority from a job description.",
    endpoint: "/api/career-tools/job-parser",
    fields: [
      {
        key: "jobDescription",
        label: "Job Description",
        type: "textarea",
        placeholder: "Paste full job description here...",
      },
    ],
    payload: (v) => ({ jobDescription: v.jobDescription || "" }),
    disabled: (v) => !has(v.jobDescription),
    buttonLabel: "Parse Job Description",
    runningLabel: "Parsing...",
    emptyMessage: "No parser output yet.",
  },
  {
    id: "ats-analysis",
    category: "core",
    title: "ATS Analysis",
    description: "Score ATS alignment between your resume and target job.",
    endpoint: "/api/career-tools/ats-analysis",
    fields: [
      {
        key: "resumeText",
        label: "Resume Text",
        type: "textarea",
        placeholder: "Paste resume text here...",
      },
      {
        key: "jobDescription",
        label: "Job Description",
        type: "textarea",
        placeholder: "Paste full job description here...",
      },
    ],
    payload: (v) => ({
      resumeText: v.resumeText || "",
      jobDescription: v.jobDescription || "",
    }),
    disabled: (v) => !has(v.resumeText) || !has(v.jobDescription),
    buttonLabel: "Run ATS Analysis",
    runningLabel: "Analyzing...",
    emptyMessage: "No ATS output yet.",
  },
  {
    id: "recruiter-scan",
    category: "core",
    minimumPlan: "pro",
    title: "Recruiter Scan",
    description: "Estimate recruiter skim readiness and detect red flags.",
    endpoint: "/api/career-tools/recruiter-scan",
    fields: [
      {
        key: "resumeText",
        label: "Resume Text",
        type: "textarea",
        placeholder: "Paste resume text here...",
      },
    ],
    payload: (v) => ({ resumeText: v.resumeText || "" }),
    disabled: (v) => !has(v.resumeText),
    buttonLabel: "Run Recruiter Scan",
    runningLabel: "Scanning...",
    emptyMessage: "No recruiter scan output yet.",
  },
  {
    id: "competitive-analysis",
    category: "core",
    minimumPlan: "pro",
    title: "Competitive Analysis",
    description: "Compare your profile against a benchmark resume.",
    endpoint: "/api/career-tools/competitive-analysis",
    fields: [
      {
        key: "resumeText",
        label: "Resume Text",
        type: "textarea",
        placeholder: "Paste resume text here...",
      },
      {
        key: "benchmarkText",
        label: "Benchmark Resume",
        type: "textarea",
        placeholder: "Paste benchmark resume text...",
      },
    ],
    payload: (v) => ({
      resumeText: v.resumeText || "",
      benchmarkText: v.benchmarkText || "",
    }),
    disabled: (v) => !has(v.resumeText) || !has(v.benchmarkText),
    buttonLabel: "Run Competitive Analysis",
    runningLabel: "Comparing...",
    emptyMessage: "No competitive output yet.",
  },
  {
    id: "role-fit",
    category: "strategy",
    title: "Role Fit",
    description:
      "Score fit against your target role and assess readiness signals.",
    endpoint: "/api/career-tools/role-fit",
    fields: [
      {
        key: "resumeText",
        label: "Resume Text",
        type: "textarea",
        placeholder: "Paste resume text here...",
      },
      {
        key: "targetRole",
        label: "Target Role",
        type: "input",
        placeholder: "e.g. Senior Backend Engineer",
      },
    ],
    payload: (v) => ({
      resumeText: v.resumeText || "",
      targetRole: v.targetRole || "",
    }),
    disabled: (v) => !has(v.resumeText) || !has(v.targetRole),
    buttonLabel: "Run Role Fit",
    runningLabel: "Scoring...",
    emptyMessage: "No role-fit output yet.",
  },
  {
    id: "salary-estimate",
    category: "strategy",
    minimumPlan: "pro",
    title: "Salary Estimate",
    description:
      "Estimate compensation range using target role, location, and experience.",
    endpoint: "/api/career-tools/salary-estimate",
    fields: [
      {
        key: "targetRole",
        label: "Target Role",
        type: "input",
        placeholder: "e.g. Senior Backend Engineer",
      },
      {
        key: "targetLocation",
        label: "Target Location",
        type: "input",
        placeholder: "e.g. London, UK",
      },
      {
        key: "yearsExperience",
        label: "Years of Experience",
        type: "input",
        placeholder: "e.g. 5",
      },
    ],
    payload: (v) => ({
      targetRole: v.targetRole || "",
      location: v.targetLocation || "",
      yearsExperience: Number(v.yearsExperience || 0),
    }),
    disabled: (v) => !has(v.targetRole),
    buttonLabel: "Estimate Salary",
    runningLabel: "Estimating...",
    emptyMessage: "No salary estimate yet.",
  },
  {
    id: "market-demand",
    category: "strategy",
    minimumPlan: "pro",
    title: "Market Demand",
    description: "Evaluate market demand and outlook for your target role.",
    endpoint: "/api/career-tools/market-demand",
    fields: [
      {
        key: "targetRole",
        label: "Target Role",
        type: "input",
        placeholder: "e.g. Senior Backend Engineer",
      },
      {
        key: "targetLocation",
        label: "Target Location",
        type: "input",
        placeholder: "e.g. London, UK",
      },
    ],
    payload: (v) => ({
      targetRole: v.targetRole || "",
      location: v.targetLocation || "",
    }),
    disabled: (v) => !has(v.targetRole),
    buttonLabel: "Analyze Market Demand",
    runningLabel: "Analyzing...",
    emptyMessage: "No market demand analysis yet.",
  },
  {
    id: "learning-roadmap",
    category: "strategy",
    title: "Learning Roadmap",
    description: "Build a practical roadmap to close skill gaps.",
    endpoint: "/api/career-tools/learning-roadmap",
    fields: [
      {
        key: "resumeText",
        label: "Resume Text",
        type: "textarea",
        placeholder: "Paste resume text here...",
      },
      {
        key: "jobDescription",
        label: "Job Description",
        type: "textarea",
        placeholder: "Paste full job description here...",
      },
    ],
    payload: (v) => ({
      resumeText: v.resumeText || "",
      jobDescription: v.jobDescription || "",
    }),
    disabled: (v) => !has(v.resumeText) || !has(v.jobDescription),
    buttonLabel: "Generate Learning Roadmap",
    runningLabel: "Generating...",
    emptyMessage: "No learning roadmap yet.",
  },
  {
    id: "visa-guidance",
    category: "strategy",
    title: "Visa Guidance",
    description:
      "Position profile for visa-oriented roles and sponsorship conversations.",
    endpoint: "/api/career-tools/visa-guidance",
    fields: [
      {
        key: "resumeText",
        label: "Resume Text",
        type: "textarea",
        placeholder: "Paste resume text here...",
      },
      {
        key: "targetRole",
        label: "Target Role",
        type: "input",
        placeholder: "e.g. Senior Backend Engineer",
      },
      {
        key: "targetLocation",
        label: "Target Location",
        type: "input",
        placeholder: "e.g. London, UK",
      },
    ],
    payload: (v) => ({
      targetRole: v.targetRole || "",
      location: v.targetLocation || "",
      resumeText: v.resumeText || "",
    }),
    disabled: (v) => !has(v.targetRole) || !has(v.targetLocation),
    buttonLabel: "Run Visa Guidance",
    runningLabel: "Guiding...",
    emptyMessage: "No visa guidance yet.",
  },
  {
    id: "application-readiness",
    category: "strategy",
    title: "Application Readiness",
    description: "Measure readiness and generate a short execution plan.",
    endpoint: "/api/career-tools/application-readiness",
    fields: [
      {
        key: "resumeText",
        label: "Resume Text",
        type: "textarea",
        placeholder: "Paste resume text here...",
      },
      {
        key: "jobDescription",
        label: "Job Description",
        type: "textarea",
        placeholder: "Paste full job description here...",
      },
      {
        key: "targetRole",
        label: "Target Role",
        type: "input",
        placeholder: "e.g. Senior Backend Engineer",
      },
    ],
    payload: (v) => ({
      resumeText: v.resumeText || "",
      jobDescription: v.jobDescription || "",
      targetRole: v.targetRole || "",
    }),
    disabled: (v) => !has(v.resumeText) || !has(v.jobDescription),
    buttonLabel: "Run Application Readiness",
    runningLabel: "Scoring...",
    emptyMessage: "No application readiness output yet.",
  },
  {
    id: "networking-strategy",
    category: "strategy",
    title: "Networking Strategy",
    description: "Define channels and cadence for networking outreach.",
    endpoint: "/api/career-tools/networking-strategy",
    fields: [
      {
        key: "resumeText",
        label: "Resume Text",
        type: "textarea",
        placeholder: "Paste resume text here...",
      },
      {
        key: "targetRole",
        label: "Target Role",
        type: "input",
        placeholder: "e.g. Senior Backend Engineer",
      },
      {
        key: "targetLocation",
        label: "Target Location",
        type: "input",
        placeholder: "e.g. London, UK",
      },
    ],
    payload: (v) => ({
      targetRole: v.targetRole || "",
      location: v.targetLocation || "",
      resumeText: v.resumeText || "",
    }),
    disabled: (v) => !has(v.targetRole),
    buttonLabel: "Build Networking Strategy",
    runningLabel: "Planning...",
    emptyMessage: "No networking strategy yet.",
  },
  {
    id: "portfolio-audit",
    category: "execution",
    title: "Portfolio Audit",
    description: "Identify proof gaps and next best portfolio artifacts.",
    endpoint: "/api/career-tools/portfolio-audit",
    fields: [
      {
        key: "resumeText",
        label: "Resume Text",
        type: "textarea",
        placeholder: "Paste resume text here...",
      },
      {
        key: "targetRole",
        label: "Target Role",
        type: "input",
        placeholder: "e.g. Senior Backend Engineer",
      },
    ],
    payload: (v) => ({
      resumeText: v.resumeText || "",
      targetRole: v.targetRole || "",
    }),
    disabled: (v) => !has(v.resumeText),
    buttonLabel: "Run Portfolio Audit",
    runningLabel: "Auditing...",
    emptyMessage: "No portfolio audit yet.",
  },
  {
    id: "offer-negotiation",
    category: "execution",
    title: "Offer Negotiation",
    description:
      "Prepare negotiation anchors, scripts, and fallback concessions.",
    endpoint: "/api/career-tools/offer-negotiation",
    fields: [
      {
        key: "targetRole",
        label: "Target Role",
        type: "input",
        placeholder: "e.g. Senior Backend Engineer",
      },
      {
        key: "targetLocation",
        label: "Target Location",
        type: "input",
        placeholder: "e.g. London, UK",
      },
      {
        key: "yearsExperience",
        label: "Years of Experience",
        type: "input",
        placeholder: "e.g. 5",
      },
    ],
    payload: (v) => ({
      targetRole: v.targetRole || "",
      location: v.targetLocation || "",
      yearsExperience: Number(v.yearsExperience || 0),
    }),
    disabled: (v) => !has(v.targetRole),
    buttonLabel: "Prepare Offer Negotiation",
    runningLabel: "Preparing...",
    emptyMessage: "No negotiation prep yet.",
  },
  {
    id: "job-search-sprint",
    category: "execution",
    title: "Job Search Sprint",
    description:
      "Generate a weekly execution sprint for applications and outreach.",
    endpoint: "/api/career-tools/job-search-sprint",
    fields: [
      {
        key: "resumeText",
        label: "Resume Text",
        type: "textarea",
        placeholder: "Paste resume text here...",
      },
      {
        key: "targetRole",
        label: "Target Role",
        type: "input",
        placeholder: "e.g. Senior Backend Engineer",
      },
      {
        key: "targetLocation",
        label: "Target Location",
        type: "input",
        placeholder: "e.g. London, UK",
      },
    ],
    payload: (v) => ({
      targetRole: v.targetRole || "",
      location: v.targetLocation || "",
      resumeText: v.resumeText || "",
    }),
    disabled: (v) => !has(v.targetRole),
    buttonLabel: "Build Job Search Sprint",
    runningLabel: "Planning...",
    emptyMessage: "No sprint plan yet.",
  },
  {
    id: "personal-brand-audit",
    category: "execution",
    title: "Personal Brand Audit",
    description:
      "Improve narrative clarity and positioning across resume/outreach.",
    endpoint: "/api/career-tools/personal-brand-audit",
    fields: [
      {
        key: "resumeText",
        label: "Resume Text",
        type: "textarea",
        placeholder: "Paste resume text here...",
      },
      {
        key: "targetRole",
        label: "Target Role",
        type: "input",
        placeholder: "e.g. Senior Backend Engineer",
      },
    ],
    payload: (v) => ({
      resumeText: v.resumeText || "",
      targetRole: v.targetRole || "",
    }),
    disabled: (v) => !has(v.resumeText),
    buttonLabel: "Run Personal Brand Audit",
    runningLabel: "Auditing...",
    emptyMessage: "No brand audit yet.",
  },
  {
    id: "career-pivot-plan",
    category: "execution",
    title: "Career Pivot Plan",
    description: "Plan a role transition with a focused 4-week strategy.",
    endpoint: "/api/career-tools/career-pivot-plan",
    fields: [
      {
        key: "resumeText",
        label: "Resume Text",
        type: "textarea",
        placeholder: "Paste resume text here...",
      },
      {
        key: "targetRole",
        label: "Target Role",
        type: "input",
        placeholder: "e.g. Senior Backend Engineer",
      },
      {
        key: "jobDescription",
        label: "Job Description",
        type: "textarea",
        placeholder: "Paste full job description here...",
      },
    ],
    payload: (v) => ({
      resumeText: v.resumeText || "",
      targetRole: v.targetRole || "",
      jobDescription: v.jobDescription || "",
    }),
    disabled: (v) => !has(v.resumeText) || !has(v.targetRole),
    buttonLabel: "Generate Career Pivot Plan",
    runningLabel: "Planning...",
    emptyMessage: "No career pivot plan yet.",
  },
  {
    id: "outreach-messages",
    category: "execution",
    title: "Outreach Messages",
    description:
      "Generate messages for cold outreach, follow-up, and referral asks.",
    endpoint: "/api/career-tools/outreach-messages",
    fields: [
      {
        key: "resumeText",
        label: "Resume Text",
        type: "textarea",
        placeholder: "Paste resume text here...",
      },
      {
        key: "targetRole",
        label: "Target Role",
        type: "input",
        placeholder: "e.g. Senior Backend Engineer",
      },
      {
        key: "targetLocation",
        label: "Target Location",
        type: "input",
        placeholder: "e.g. London, UK",
      },
    ],
    payload: (v) => ({
      targetRole: v.targetRole || "",
      location: v.targetLocation || "",
      resumeText: v.resumeText || "",
    }),
    disabled: (v) => !has(v.targetRole),
    buttonLabel: "Generate Outreach Messages",
    runningLabel: "Writing...",
    emptyMessage: "No outreach messages yet.",
  },
  {
    id: "interview-prep",
    category: "execution",
    title: "Interview Prep",
    description: "Get tailored interview questions and coaching priorities.",
    endpoint: "/api/career-tools/interview-prep",
    fields: [
      {
        key: "resumeText",
        label: "Resume Text",
        type: "textarea",
        placeholder: "Paste resume text here...",
      },
      {
        key: "jobDescription",
        label: "Job Description",
        type: "textarea",
        placeholder: "Paste full job description here...",
      },
      {
        key: "answerText",
        label: "Interview Answer (Optional)",
        type: "textarea",
        placeholder: "Paste answer for feedback...",
      },
    ],
    payload: (v) => ({
      resumeText: v.resumeText || "",
      jobDescription: v.jobDescription || "",
      answerText: v.answerText || "",
    }),
    disabled: (v) => !has(v.resumeText) || !has(v.jobDescription),
    buttonLabel: "Run Interview Prep",
    runningLabel: "Preparing...",
    emptyMessage: "No interview prep output yet.",
  },
  {
    id: "interview-drill-plan",
    category: "execution",
    title: "Interview Drill Plan",
    description: "Create a drill cadence and question set for interview reps.",
    endpoint: "/api/career-tools/interview-drill-plan",
    fields: [
      {
        key: "jobDescription",
        label: "Job Description",
        type: "textarea",
        placeholder: "Paste full job description here...",
      },
      {
        key: "targetRole",
        label: "Target Role",
        type: "input",
        placeholder: "e.g. Senior Backend Engineer",
      },
      {
        key: "answerText",
        label: "Interview Answer (Optional)",
        type: "textarea",
        placeholder: "Paste answer for feedback...",
      },
    ],
    payload: (v) => ({
      jobDescription: v.jobDescription || "",
      targetRole: v.targetRole || "",
      answerText: v.answerText || "",
    }),
    disabled: (v) => !has(v.jobDescription) && !has(v.targetRole),
    buttonLabel: "Generate Interview Drill Plan",
    runningLabel: "Drilling...",
    emptyMessage: "No interview drill plan yet.",
  },
];

export const TOOL_MAP = Object.fromEntries(
  CAREER_LAB_TOOLS.map((tool) => [tool.id, tool]),
);
